"""empty message

Revision ID: 956eba64c753
Revises: 846f27a7777d
Create Date: 2017-06-04 21:24:02.718000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '956eba64c753'
down_revision = '846f27a7777d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
